services:
  0095.backend:
    image: njavilas/helloword:go
    expose:
      - 8080

    environment:
      - SERVER_NAME=0095

    networks:
      example:
        aliases:
          - 0095.backend.example.net

  0095.frontend:
    image: njavilas/helloword:nginx
    expose:
      - 80

    networks:
      example:
        aliases:
          - 0095.frontend.example.net

  0095.proxy:
    image: njavilas/proxy:nginx
    ports:
      - "7000:80"

    environment:
      - FRONTEND_SERVER_NAME=0095.frontend.example.net
      - FRONTEND_SERVER_PORT=80

      - BACKEND_SERVER_NAME=0095.backend.example.net
      - BACKEND_SERVER_PORT=8080

    networks:
      example:
        aliases:
          - 0095.example.net

networks:
  example:
    external: true